---
title: "k-fold CV for lmer and mboost model"
author: "Anuradha Ramachandran"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(PGEE)
data(yeastG1)
yeast = yeastG1
```

```{r}
set.seed(1)
k = 4
n <- nrow(yeast)

k_fold_samples <- function(n, k=4){
# Initialize a list to store sampled points for each fold
fold_samples <- vector("list", length = k)
# Group genes by geneid
gene_groups <- split(yeast, yeast$id)
  for (gene in gene_groups){
    sampled_indices <- sample(1:nrow(gene), size = 4, replace = FALSE)
    sampled_points <- gene[sampled_indices, ]
    # Assign sampled points to the each fold
    for(i in 1:k){
      fold_samples[[i]] <- rbind(fold_samples[[i]], sampled_points[i, ])
    }
  }  
return(fold_samples)
}

```




```{r}
library(mboost)
library(lme4)
k_fold_rmse <- function(fold_samples, k, model_name){

# Initialize a vector to store RMSE values for each fold
fold_rmse <- numeric(k)
# Loop through each fold
for (i in 1:k) {
  # Initialize validation set for the current fold
  validation_set <- fold_samples[[i]]
  
  # Initialize training set
  training_set <- data.frame()
  
  # Concatenate samples from all other folds for training set
  for (j in 1:k) {
    if (j != i) {
      training_set <- rbind(training_set, fold_samples[[j]])
    }
  }
  
  if(model_name == 'lmer'){
    model <- lmer(y ~ time + (1 | id), data = training_set)
   # Get predictions for the validation set using the model
    predictions <- predict(model, newdata = validation_set)
  }
  if(model_name == 'mboost'){
    #repeat for mboost model as well
  }
   

  # Calculate RMSE
  rmse <- sqrt(mean((validation_set$y - predictions)^2))
  
  # Store the RMSE for the current fold
  fold_rmse[i] <- rmse
}
return(mean(fold_rmse))
}
```



```{r}
set.seed(1)
k = 4
n <- nrow(yeast)
fold_samples = k_fold_samples(n,k)
lmer_rmse = k_fold_rmse(fold_samples, k, 'lmer')
print(lmer_rmse)
```


